[build]
  command = "git submodule sync && git submodule update --init --recursive && hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.127.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
